'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import Providers from '~/utils/provider'
import Analytics from '~/utils/Analytics'
import MainLayout from '~/components/layouts/Main'
import { Suspense } from 'react'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export const dynamic = 'force-dynamic'

export default function RootLayout({ children }) {
  return (
    <html lang='en' className='light'>
      <head>
        <meta name='referrer' content='no-referrer' />
      </head>
      <body className={inter.className}>
        <Suspense>
          <Analytics />
        </Suspense>
        <Providers>
          <MainLayout>{children}</MainLayout>
        </Providers>
      </body>
    </html>
  )
}
